### ISSUE TITLE
Hide/Show issue for rendering

### ISSUE THREAD

**Issue by dacre-j** [angular-ui/ui-calendar#114]
Hi,

I have a problem with ui-calendar. If the calendar is displayed when the html page is generated, there is no issue, we can manipulate it. But if it is hide during the generation and then displayed, only the header is visible.
I edited a fiddle to explicit the issue. There is a button which enable the display of the first calendar, hide in generation, and a second calendar already displayed at the generation :
http://jsfiddle.net/fECuY/20/

Thanks for your help.

**Comment by poliveira89** [comment]
This is happening with me as well.
I tired the example fo  @joshkurz since he closed the issues, and for did not worked at all.

So I tried the JSFiddle of @dacre-j and happens the exact same problem as mine, so I have forked into this: http://jsfiddle.net/zhne0fmw/
To test "render", "rerenderEvents" and "refetchEvents" after the show/hide action.
