### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by Karttin** [angular-ui/ui-calendar#118]
Hello I am using ui-calendar in my project, all works beautifully in desktop.

When I try to look in mobile, calendar works as expected. (I am using day view only)

when I click/tap  - eventClick works fine. 

But I couldn't create a new event, when I try to do full calendar moves up and down. If I tap on a single place it creates the event but unable to resize the event?

Any help appreciated.

Kind Regards
Kay

**Comment by lubochka** [comment]
I was struggling with issue for several days. The reason was that UI touch punch completely disabled all my form functionality. Also I needed some special event for click functionality
So what did I do at the end?
1. I added special id to the calendar component. So that way I could change the natural behavior only for the events in this area
2. Added eventAfterRender event:
eventAfterRender: function (event, element) {
                    if (isMobile.phone) { //optional: there is angular library for that

                        $(element).ready(function () {  //
                            $(element).draggable(); 
                        });
                        $(element).on('click', function () { //optional
                            $scope.GetTask(event.id); //some click event I need
                        })

                    }

                }
