### ISSUE TITLE
Support for Angular 1.3

### ISSUE THREAD

**Issue by domiko** [angular-ui/ui-calendar#178]
Hi.

Are there any plans to support AngularJS 1.3 ?

Regards

**Comment by petrsimon** [comment]
I've ran into an error where `eventSources` were `undefined`, which was due to a late assignment of `$scope.eventSources`. There should probably be a measure against that, perhaps just  `$scope.eventSources = [];` in `uiCalendarController`, otherwise it's up to the user to initialize it with an empty array. 
Other than that it works fine for me with Angular 1.3.6. Cheers

**Comment by juristr** [comment]
Hi, anyone knows what I'm doing wrong in my example: http://plnkr.co/edit/4wTDO04c9gkcPgqzWux8?p=preview

I'm able to add events through the ng-model but all the click events like when clicking on a day or existing event don't work...(not to speak about drag&drop on events).

Does anyone have an idea? Thx

**Comment by joshkurz** [comment]
two reasons @juristr, you were not passing in the options to the calendar correctly, and you were assigning the vm.clickFunctions, as variables, after they were being set on the options object. Here is a fix, which sets the functions as a function and not a variable, allowing for the runtime context to contain its information, by the time you set it on the options. http://plnkr.co/edit/dn1c9f8M2kM0p5hDR1fR?p=preview 

Closing this now, as the calendar supports AngularJS 1.3.x

**Comment by juristr** [comment]
@joshkurz Ya, have figured it out meanwhile. Silly mistake on my side. Anyway, thx for the Plunker.

**Comment by genuinefafa** [comment]
@joshkurz if it is indeed supported why does the `bower.json` requires 1.2.x? [here](https://github.com/angular-ui/ui-calendar/blob/master/bower.json)
