### ISSUE TITLE
Getting undefined for "calendar.fullCalendar" in scope .init

### ISSUE THREAD

**Issue by mrjeje64** [angular-ui/ui-calendar#220]
Hello everyone,

I am new user to ui calendar and cannot get it to work. I have the following error : 
TypeError: undefined is not a function
    at Scope.link.scope.init (calendar.js:245)

I use Angular 1.2.6, jquery 2.0.3.

Initialization in Angular is correct. All js files are present.

I declared the div containing the calendar this way:
<div ui-calendar class="calendar" ng-model="eventSources"></div>

I logged the calendar object in scope.init : 
 calendar ,  [div.calendar.ng-isolate-scope.ng-pristine.ng-valid, selector: "", context: div.calendar.ng-isolate-scope.ng-pristine.ng-valid, jquery: "2.0.3", constructor: function, init: function…]0: div.calendar.ng-isolate-scope.ng-pristine.ng-validcontext: div.calendar.ng-isolate-scope.ng-pristine.ng-validlength: 1selector: ""__proto__: jQuery[0]

I surely have missed something. Would appreciate the help.

Thanks in advance

**Comment by kornelc** [comment]
I was having the same exact issue today. I had to move the jquery and jquery-ui scripts before angular. Then it worked. The UI comes up fine now.

**Comment by mrjeje64** [comment]
You saved my day !!! Works fine now
I really haven't thought about that. 

My fullcalendar.js script was after angular.js.

Thank you so much.

**Comment by diegofu** [comment]
Thank you so much!!!!! I was having exactly the same issue.

**Comment by jakeapeters** [comment]
I just came across this issue too. I'm using Angular 1.3.15 + Bootstrap 3 and the only order of .js files that works for me is:

* Angular
* jQuery
* jQuery UI
* Bootstrap 
* Moment
* FullCalendar

I hope that saves someone a bit of frustration in the future!

**Comment by kornelc** [comment]
I think that might cause a problem because your app will use two versions of jQuery. As far as I understand Angular uses a dumbed down version of jQuery. Calendar needs a real one including ui. If you include jQuery after Angular, then Angular will use its own version and Calendar will use the one you included. If you include it before Angular, they will both use the same version, which I think is much cleaner (I read it somewhere in Angular ui that this way you can force it to use a full version.). Maybe, your Angular's version is not compatible with the jQuery you included. I definitely think you should include it before to avoid multiple versions of jQuery being used on your page. I think that can become a source of confusion.
It makes it all the more confusing because calendar will not fail as cleanly as it probably would without Angular in there, since it thinks jQuery is there. Even though it's not quite there.

**Comment by femebaApp** [comment]
Thanks jakeapeters, i've solved the problem simply changing order of my scripts! Thats good, i wasn't knew that the order affect this...

**Comment by gevindu1990** [comment]
k7k
