### ISSUE TITLE
Terribly slow loading (less then 150 events)

### ISSUE THREAD

**Issue by starf** [angular-ui/ui-calendar#235]
It takes from minutes (on slow mobile devices) to tens of seconds on faster pc's.
Can anyone please give some sort of explanation or solution? It's driving my users (and myself) crazy.
Thanks.

**Comment by joe-schorn** [comment]
Are you adding events one at a time in a loop? Or starting by adding array of events to the eventSources? 

If you are pushing them to your events array one at a time, it would be slow because the eventWatcher is calling 'renderEvent.' Render event would be causing the calendar to rerender every time an event is added.  

See this stackoverflow: http://stackoverflow.com/questions/1924336/jquery-fullcalendar-fetch-event-optimization

You want to add a new eventSource rather than adding events individually.

**Comment by starf** [comment]
You just made my day. Thanks a million times.
