### ISSUE TITLE
Edit calendar options after init

### ISSUE THREAD

**Issue by infomanPMF** [angular-ui/ui-calendar#242]
Can someone explain how can I edit the calendar after the calendar is initialized. 
I tried by directly assigning options to $scope.uiConfig.calendar afterward i.e.
$scope.uiConfig.calendar.hiddenDays = $scope.hidden_days;
but it crashes the calendar.
Thanks

**Comment by LilBiggs** [comment]
So this issue is a little old, but I figure I would create a plunker anyway and show a solution that works. If you are still having issues please create a plunker with your scenario. Basically my test waits for the calendar to initialize, then sets the hiddenDays to 4. (To hide Thursday)

http://plnkr.co/edit/SDkfiF?p=preview

**Comment by joshkurz** [comment]
yeah currently there is no init callback, so @LilBiggs method does work. However I would suggest to close the watch function out if not needed, once the initialization has happened.
