### ISSUE TITLE
Request: Year view

### ISSUE THREAD

**Issue by aboalwi** [angular-ui/ui-calendar#383]
I'm not sure where i put a request so i ended up here

Can we have yearly view just like the one here:
[http://epsy.ldtp.net/fullcalendar/demos/year.html](http://epsy.ldtp.net/fullcalendar/demos/year.html)
From [https://github.com/tpruvot/fullcalendar](https://github.com/tpruvot/fullcalendar)

Thanks

**Comment by flick36** [comment]
You can create your [own views](http://fullcalendar.io/docs/views/Custom_Views/)

you have the advantage that the one you want it's already created on the example you post yourself, simply go to the [modified fullcalendar](http://epsy.ldtp.net/fullcalendar/dist/fullcalendar.js) of the example  and searh for : 

> fcViews.year = View.extend({

then you'll see that it's exactly the same thing the official documentation ask you to do in order to create a custom view

now if you don'nt understand how to do it, you can just use that modified library instead, if that's the only thing he change on it, it should work with ui-calendar but that fullcalendar version it's the 2.2.3 so you might lose some features addes post that version

**Comment by W-prog** [comment]
Hi, have you solve your request ?
Cos' i wanna make a view year with month in column, day in row. you know.
Can i make this with custom view ? https://fullcalendar.io/docs/views/Custom_Views/
